### ISSUE TITLE
Usage with dep

### ISSUE THREAD

**Issue by bmuschko** [ToQoz/gopwt#36]
I am having some trouble using gopwt in conjunction with dep. Instead of using `go get` I only want to resolve my dependencies via `dep ensure`.

**Gopkg.toml:**

```
[[constraint]]
  name = "github.com/ToQoz/gopwt"
  version = "v1.2.0"
```

I see all the right dependencies in my `vendor` directory. However upon executing my test I get the following error message:

```
# github.com/bmuschko/go-testing-frameworks/calc_gopwt_test
/var/folders/02/3dgzjkqj4kz0g7lnrk0w93c00000gn/T/186407672/src/github.com/bmuschko/go-testing-frameworks/calc_gopwt_test/calc_gopwt_test.go:8:2: cannot find package "github.com/ToQoz/gopwt/translatedassert" in any of:
	/usr/local/Cellar/go/1.10.2/libexec/src/github.com/ToQoz/gopwt/translatedassert (from $GOROOT)
	/var/folders/02/3dgzjkqj4kz0g7lnrk0w93c00000gn/T/186407672/src/github.com/ToQoz/gopwt/translatedassert (from $GOPATH)
	/Users/bmuschko/go/src/github.com/ToQoz/gopwt/translatedassert
FAIL	github.com/bmuschko/go-testing-frameworks/calc_gopwt_test [setup failed]
exit status 1
```

My test roughly look like this:

**calc_gopwt_test.go:**

```
package calc_gopwt_test

import (
	"flag"
	"github.com/ToQoz/gopwt"
	"os"
	. "github.com/bmuschko/go-testing-frameworks/calc"
	"github.com/ToQoz/gopwt/assert"
	"testing"
)

func TestMain(m *testing.M) {
	flag.Parse()
	gopwt.Empower()
	os.Exit(m.Run())
}

func TestAdd(t *testing.T) {
	result := Add(1, 2)
	assert.OK(t, 3 == result)
}
```

The test file sits in a separate `*_test` package. Do you have an idea what might be going on? Happy to push some code to a branch if needed. It seems I can only make this work when installing the necessary packages via `go get`.

**Comment by ToQoz** [comment]
Thank you for report.
Use with `dep` is not tested yet because of I'm not use it. Please give me some time for check & fix.

**Comment by ToQoz** [comment]
@bmuschko 

There was a gopwt's bug.
I've fixed in #37 and published `v1.3.0`. Please bump gopwt version of Gopkg.toml.

**Comment by bmuschko** [comment]
@ToQoz Thanks for looking at it. With version `v1.3.0` I still seem to experience the same issue. Would you mind having another look? You may want to remove the packages from your `GOPATH` directory to reproduce the issue.

**Comment by ToQoz** [comment]
Maybe your vendor directory is parent directory of calc_gopwt_test.go ?

**Comment by bmuschko** [comment]
@ToQoz I pushed the code to the branch https://github.com/bmuschko/go-testing-frameworks/tree/gopwt. The `vendor` directory sits next to `calc` which contains the test case. Feel free to strip down the code so that only gopwt is used as a single testing framework. That might make it a bit easier to debug the issue.

**Comment by ToQoz** [comment]
@bmuschko Thank you.

current status in #39.

Probably vendoring issue is fixed. But I would need some time to merge because it is too slow and [works only with go1.10](https://github.com/ToQoz/gopwt/pull/39/files#diff-4e365ba81d21f167f7f5612a765e481bR95).

```
$ go get github.com/bmuschko/go-testing-frameworks
$ cd $GOPATH/src/github.com/bmuschko/go-testing-frameworks
$ git checkout gopwt
$ dep ensure
$ mv $GOPATH/src/github.com/ToQoz/gopwt $GOPATH/src/github.com/ToQoz/gopwt.bak
$ mv $GOPATH/pkg/darwin_amd64/github.com/ToQoz/gopwt  $GOPATH/pkg/darwin_amd64/github.com/ToQoz/gopwt.bak
$ mv $GOPATH/pkg/darwin_amd64/github.com/ToQoz/gopwt.a  $GOPATH/pkg/darwin_amd64/github.com/ToQoz/gopwt.a.bak
$ go test ./calc
# github.com/bmuschko/go-testing-frameworks/calc_test
/var/folders/rv/4tv6zq8n6bl_jvdpbp1fmvjc0000gn/T/754401231/src/github.com/bmuschko/go-testing-frameworks/calc/calc_gopwt_test.go:5:2: imported and not used: "github.com/bmuschko/go-testing-frameworks/vendor/github.com/ToQoz/gopwt/translatedassert"
/var/folders/rv/4tv6zq8n6bl_jvdpbp1fmvjc0000gn/T/754401231/src/github.com/bmuschko/go-testing-frameworks/calc/calc_gopwt_test.go:14:2: undefined: Empower
/var/folders/rv/4tv6zq8n6bl_jvdpbp1fmvjc0000gn/T/754401231/src/github.com/bmuschko/go-testing-frameworks/calc/calc_gopwt_test.go:19:2: undefined: OK
/var/folders/rv/4tv6zq8n6bl_jvdpbp1fmvjc0000gn/T/754401231/src/github.com/bmuschko/go-testing-frameworks/calc/calc_gopwt_test.go:23:2: undefined: OK
/var/folders/rv/4tv6zq8n6bl_jvdpbp1fmvjc0000gn/T/754401231/src/github.com/bmuschko/go-testing-frameworks/calc/calc_gopwt_test.go:27:2: undefined: OK
/var/folders/rv/4tv6zq8n6bl_jvdpbp1fmvjc0000gn/T/754401231/src/github.com/bmuschko/go-testing-frameworks/calc/calc_gopwt_test.go:31:2: undefined: OK
FAIL    github.com/bmuschko/go-testing-frameworks/calc [build failed]
exit status 2
FAIL    github.com/bmuschko/go-testing-frameworks/calc  13.213s
go test ./calc  53.41s user 13.20s system 403% cpu 16.500 total
```

---

Separate matter gopwt is not compatible with `import . "github.com/ToQoz/gopwt"`.  I've issued #40. I'm going to fix it next to this.

**Comment by bmuschko** [comment]
Work now. Thanks!

**Comment by bmuschko** [comment]
FYI: I covered gopwt in this blog post: https://bmuschko.com/blog/go-testing-frameworks/#gopwt
